export * from "./listsActions";
export * from "./cardsActions";

export const CONSTANTS = {

    DRAG_HAPPENED: "DRAG_HAPPENED",
    CREATE_NEW_BOARD: 'CREATE_NEW_BOARD',
    CANCEL_NEW_BOARD: 'CANCEL_NEW_BOARD',
    SUBMIT_NEW_BOARD: 'SUBMIT_NEW_BOARD',
    RECEIVE_NEW_BOARD: 'RECEIVE_NEW_BOARD',
    CLEAN_NEW_BOARD: 'CLEAN_NEW_BOARD',
    SELECT_ACTIVE_BOARD: 'SELECT_ACTIVE_BOARD',
    STORE_NEW_BOARD_TO_COLLECTION: 'STORE_NEW_BOARD_TO_COLLECTION',
    SELECT_ACTIVE_BOARD_SUCCESS: 'SELECT_ACTIVE_BOARD_SUCCESS',
    LIST_EDIT_MODE_ENABLED: 'LIST_EDIT_MODE_ENABLED',
    STOP_EDITING_LIST: 'STOP_EDITING_LIST',
    SUBMIT_LIST: 'SUBMIT_LIST',
    SUBMIT_LIST_SUCCESS: 'SUBMIT_LIST_SUCCESS',
    SUBMIT_NEW_CARD: 'SUBMIT_NEW_CARD',
    HANDLE_DROP: 'HANDLE_DROP',
    ARCHIVE_POST: 'ARCHIVE_POST',
    ADD_CARD: "ADD_CARD",
    ADD_LIST: "ADD_LIST",
};


